# CONFIG Variables
#   This contains secure account information.
#   These are merged into the CONFIG hash via
#   the config/application.rb file.
# 
#   This app must have a correctly configured 
#	config/application.rb file to function as
#   designed.
################################################

testy: "this is my testy string"


#  Secret token for config/initializers/secret_token.rb
#  You can use `rake secret` to generate a secure secret key.
secret_token: "abc123_EDIT_ME"
